# Generated by Django 3.2.17 on 2023-02-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cusId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('gender', models.CharField(max_length=255)),
                ('id_proof', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('alternate_phone', models.IntegerField()),
                ('fax', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('addressproof', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.state')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
