# Generated by Django 3.2.17 on 2023-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
