# Generated by Django 3.2.17 on 2023-02-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('ct_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('st_id', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('st_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('cid', models.IntegerField()),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uId', models.IntegerField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('gender', models.CharField(max_length=255)),
                ('id_proof', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=255)),
                ('alternate_phone', models.IntegerField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('addressproof', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('gst_no', models.IntegerField(max_length=25)),
                ('zip', models.IntegerField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.state')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
