# Generated by Django 3.2.17 on 2023-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230225_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
