# Generated by Django 3.2.17 on 2023-02-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_userdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.TextField(),
        ),
    ]
