# Generated by Django 3.2.17 on 2023-02-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('venId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('gender', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('areaandstreet', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('addressproof', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip', models.IntegerField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.state')),
            ],
            options={
                'db_table': 'Vendor',
            },
        ),
    ]
